myapp/urls.py
from django.urls import path
from . import views
from django.contrib import admin

app_name = 'myapp'
urlpatterns = [
    path('',views.index),
    path('products/',views.products, name="products"),
    path('products/<int:id>/',views.product_detail, name='product_detail'),
    path('products/add',views.add_product, name="add_product"),
    path('products/update/<int:id>/',views.update_product,name="update_product"),
    path('products/delete/<int:id>/', views.delete_product, name="delete_product"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/',include('myapp.urls')),
    path('users/',include('users.urls')),

]

urlpatterns+= static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib.auth import views as authentication_view

app_name = 'users'

urlpatterns = [
    path('register/',views.register, name="register"),
    path('login/',authentication_view.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',authentication_view.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('profile/',views.profile,name='profile'),
    path('createprofile/',views.createprofile, name="createprofile")
]

myapp/models.py
from django.db import models

# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    desc = models.CharField(max_length=200)
    image = models.ImageField(blank=True, upload_to='images')
    
    def __str__(self):
        return self.name

users/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    def __str__(self):
        return self.user.username
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='media/images')
    contact_number = models.CharField(max_length=100,default='999999999')

users/forms.py
from calendar import c
from dataclasses import fields
import re
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True,widget=forms.EmailInput(attrs={'class':'focus:outline-none','placeholder':'buyandsell@email.com'}))
    username = forms.CharField(required=True,widget=forms.TextInput(attrs={'class':'focus:outline-none','placeholder':'Frank123'}))
    password1 = forms.CharField(required=True,widget=forms.PasswordInput(attrs={'class':'focus:outline-none'}))
    password2 = forms.CharField(required=True,widget=forms.PasswordInput(attrs={'class':'focus:outline-none'}))

    class Meta:
        model = User
        fields = ('username','email','password1','password2')

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user    

myapp/views.py
from curses.ascii import HT
from multiprocessing import context
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Product

# Create your views here.

def index(request):
    return HttpResponse("Hello World!")

def products(request):
    products = Product.objects.all()
    context = {
        'products':products
    }
    return render(request, 'myapp/index.html',context)

def product_detail(request,id):
    product = Product.objects.get(id=id)
    context = {
        'product':product
    }
    return render(request, 'myapp/detail.html', context)

def add_product(request):
    if request.method == 'POST':
       name = request.POST.get('name')
       price = request.POST.get('price')
       desc = request.POST.get('desc')
       image = request.FILES['upload']
       product = Product(name=name,price=price,desc=desc,image=image) 
       product.save()
    return render(request, 'myapp/addproduct.html')

def update_product(request, id):

    product = Product.objects.get(id=id)

    if request.method =='POST':
        product.name = request.POST.get('name')
        product.price = request.POST.get('price')
        product.desc = request.POST.get('desc')
        product.image = request.FILES['upload']
        product.save()
        return redirect('/myapp/products')
    context = {
        'product':product
    }
    return render(request,'myapp/updateproduct.html', context)

def delete_product(request, id):
    product = Product.objects.get(id=id)
    context = {
        'product':product,
    }
    if request.method == 'POST':
        product.delete()
        return redirect('/myapp/products')
    return render(request,'myapp/deleteproduct.html',context)

users/views.py
from importlib.resources import contents
from django.shortcuts import render, redirect
from .forms import NewUserForm
from django.contrib.auth.decorators import login_required


def register(request):
    if request.method == 'POST':
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            return redirect('myapp/products')

    form = NewUserForm()
    context = {
        'form':form,
    }
    return render(request, 'users/register.html', context)

@login_required 
def profile(request):
    return render(request, 'users/profile.html')

def createprofile(request):
    return render(request, 'users/createprofile.html')

myapp/templates/myapp/addproduct.html
{% extends 'myapp/base.html' %}
{% block content %}
<h1 class="text-2xl m-10 font-bold">⨭Add Product</h1>
<form class="w-3/5 bg-white shadow-md m-10 px-8 py-8" method="POST" enctype="multipart/form-data" action="">
    {% csrf_token %}
    <div class="mb-4">
        <label for="" class="block text-gray-700 text-sm font-bold mb-2">Product Name</label>
        <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" type="text" name="name" id="name">
    </div>
    <div class="mb-4">
        <label for="" class="block text-gray-700 text-sm font-bold mb-2">Price</label>
        <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" type="text" name="price" id="price">
    </div>
    <div class="mb-4">
        <label for="" class="block text-gray-700 text-sm font-bold mb-2">Product Description</label>
        <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700"  type="text" name="desc" id="desc">
    </div>
    <div class="mb-4">
        <label for="" class="block text-gray-700 text-sm font-bold mb-2">Product Images</label>
        <input class="py-2" type="file" accept="image/*" name="upload" id="upload">
    </div class="mb-4">
    <div class="pt-2 pb-3">
    <input class="bg-green-500 text-white px-5 py-2" placeholder="submit" type="submit" value="Add Product" name="Add Product" id="">
    </div>
  
</form>
{% endblock %}

myapp/templates/myapp/base.html
{% load static %}
<html>

    <head>
        <link rel="stylesheet" href="{% static 'myapp/styles.css' %}">

    </head>
    <body>
        <nav class="bg-white shadow-lg">
            <div class="max-w-6xl mx-auto px-4">
                <div class="flex justify-between">
                    <div class="flex space-x-8">
                        <div>
                            <a href="{% url 'myapp:products' %}" class="flex items-center px-2 py-4"><img class="h-8 w-8" src="{% static 'myapp/images/shopping.png' %}" alt=""><span class=" flex items-center text-gray-500 font-semibold text-lg" >Buy&Sell</span></a>
          
     
                        </div>
                        <div class="flex items-center space-1">
                            <a href="{% url 'myapp:products' %}" class="py-4 px-2 text-gray-500 font-semibold border-b-4 border-green-500">Home</a>
                            <a href="" class="py-4 px-2 text-gray-500 font-semibold">About</a>
                            <a href="" class="py-4 px-2 text-gray-500 font-semibold">Contact</a>
                            {% if user.is_authenticated %}
                                <a class="py-4 px-40 text-gray-500 font-semibold" href="{% url 'users:logout' %}">Logout</a>
                                <a class="py-4 px-40 text-gray-500 font-semibold" href="{% url 'users:profile' %}">Profile</a>
                            {% else %}
                                <a class="py-4 px-40 text-gray-500 font-semibold" href="{% url 'users:login' %}">Login</a>
                            {% endif %}   
                        </div>
                    </div>
                </div>
            </div>
        </nav>


        {% block content %}



        {% endblock %}
    </body>

</html>

myapp/templates/myapp/deleteproduct.html
{% extends 'myapp/base.html' %}
{% block content %}

    <h1 class="text-2xl m-10 font-bold">Delete Product</h1>
    <form class="bg-white shadow-md m-10 w-3/5 rounded px-8 pt-6 pb-8 mb-4" method="POST"action="">
        {% csrf_token %}
        <div class="mb-4">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="">Are you sure you want to delete this product?</label>
        </div>

        <div class="block text-gray-700 text-sm font-bold mb-2" class="mb-4">
            <label for="">
                {{product.name}}
            </label>
        </div>
        <div class="pt-2 mb-4">
            <img class="w-25 h-40" src="{{product.image.url}}" alt="">
        </div>

        <div class="pt-10 mb-4">
            <input class="bg-red-500 text-white px-5 py-2" type="submit" name="Confirm" value="Confirm">
            <a class="button bg-green-500 hover:bg-green-600 
            active:bg-green-700 focus:outline-none focus:ring-green-300 
            text-white px-6 py-2" href="{% url 'myapp:products' %}">Cancel</a>
        </div>

    </form>




{% endblock %}

myapp/templates/myapp/detail.html
{% extends 'myapp/base.html' %}

{% block content %}
<html lang="en">

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Product Details</title>

    <div class="flex p-10 w-full h-200">
        <img class="w-1/3" src="{{product.image.url}}" alt="">
        <div class="w-2/3 text-xl ml-10 mt-10">
            <div class="mt-5"> <span class="text-green-500">Product name:</span>{{product.name}}</div>
            <div class="mt-5"> <span class="text-green-500">Price:</span>{{product.price}}€</div>
            <div class="mt-5 text-gray-700"><span class="text-green-500">Product description:</span>{{product.desc}}</div>
        </div>
    </div>

{% endblock %}

myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}
{% load static %}
{% block content %}

<!--Site hero starts here-->
<main class="mt-10 mx-auto max-w-7xl px-4 sm:st-12 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 xl:mt-28">
    <div class="sm:text-center lg:text-left">
        <h1 class="text-4xl font-extrabold text-gray-900 sm:text-5xl md:text-8xl">
            <span class="block xl:inline">Premium Products</span>
            <span class="block text-green-500 xl:inline">Non-Premium Prices</span>
        </h1>
        <p class="mt-3 text-base text-gray-500 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl lg:mx-0">Get the best quality used products across the globe, Free shipping </p>
    </div>
</main>
<!--Site hero ends here-->
<div class="flex mt-5 p-10 justify-center">
    <h2 class="text-3xl font-normal mt-0 mb-2 text-gray-500">Recent Products</h2>
</div>
   
<div class="p-10 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3 xl:grid-cols-3 lg:grid-cols-3 gap-5">
<!-- Card 1-->
    {% for product in products %}
    <a href="{% url 'myapp:product_detail' product.id %}">
    <div class="rounded overflow-hidden shadow-lg">
        <img class="w-full" src="{{product.image.url}}" alt="">
        <div class="px-6 py-4">
            <div class="font-bold text-xl mb-2">{{product.name}}</div>
            <div class="font-bold text-xl text-green-500">{{product.price}}€</div>
            <div class="text-gray-700 mb-2">{{product.desc}}</div>
        </div>
    </div> 
    </a>
    {% endfor %}
</div>
   

{% endblock %}

myapp/templates/myapp/updateproduct.html
{% extends 'myapp/base.html' %}
{% block content %}
<h1 class="text-2xl m-10 font-bold">Update Product</h1>
<form class="w-3/5 bg-white shadow-md m-10 px-8 py-8" method="POST" enctype="multipart/form-data" action="">
    {% csrf_token %}
    <div class="mb-4">
        <label for="" class="block text-gray-700 text-sm font-bold mb-2">Product Name</label>
        <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" value="{{product.name}}" type="text" name="name" id="name">
    </div>
    <div class="mb-4">
        <label for="" class="block text-gray-700 text-sm font-bold mb-2">Price</label>
        <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" value="{{product.price}}" type="text" name="price" id="price">
    </div>
    <div class="mb-4">
        <label for="" class="block text-gray-700 text-sm font-bold mb-2">Product Description</label>
        <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" value="{{product.desc}}" type="text" name="desc" id="desc">
    </div>
    <div class="mb-4">
        <img class="w-20 h-20" src="{{product.image.url}}" alt="">
        <label for="" class="block text-gray-700 text-sm font-bold mb-2">Product Images</label>
        <input class="py-2" type="file" accept="image/*" name="upload" id="upload">
    </div class="mb-4">

    <div class="pt-2 pb-3">
    <input class="bg-green-500 text-white px-5 py-2" placeholder="submit" type="submit" value="Update Product" name="Update Product" id="">
    </div>
  
</form>
{% endblock %}

users/templates/users/createprofile.html
{% extends 'myapp/base.html' %}
{% block content %}
    <form action="" method="POST" enctype="multipart/form-data" class="bg-white shadow-md m-10 w-3/5 rounded px-8 pt-6 pb-8 mb-4">
        {% csrf_token %}
        <div class="mb-4">
            <label class="font-bold" for="">Upload Porfile Image</label>
            <input class="py-2" placeholder="Upload a clear profile image" type="file" accept="image/*" name="upload" id="upload" >
        </div>
        <div class="mb-4">
            <label class="font-bold" for="">Contact Number</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" placeholder="999999999" type="text" name="contact_number" id="contact_number" >
        </div>
        <input class="button bg-green-500 hover:bg-green-600 
        active:bg-green-700 focus:outline-none focus:ring-green-300 
        text-white px-5 py-2" name="Add"value="Add"type="submit">
    </form>


{% endblock %}

users/templates/users/login.html
{% extends 'myapp/base.html' %}
{% block content %}

<h1 class="text-2xl m-10 font-bold">Login User</h1>
<div class="container ">
    <form class="w-2/5  bg-white shadow-md m-10 rounded px-8 pt-6 pb-8 mb-4 " method="POST">
        {% csrf_token %}
        <div class="mb-2">
            <label class="block text-gray-700 text-sm font-bold mb-2"for="">Username</label>
            <div class="shadow apperance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">
                {{ form.username }}
            </div>

        <div class="mb-2">
            <label class="block text-gray-700 text-sm font-bold mb-2"for="">Password</label>
            <div class="shadow apperance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">
                {{ form.password }}
            </div>
        </div>

        <div class="pt-2">
            <button class="button bg-green-500 hover:bg-green-600 
            active:bg-green-700 focus:outline-none focus:ring-green-300 
            text-white px-6 py-2" type="submit">Login</button>
        </div>
    </form>
</div>



{% endblock %}

users/templates/users/logout.html
{% extends 'myapp/base.html' %}
{% block content %}

<h1>You have been logged out</h1>




{% endblock %}

users/templates/users/lougout.html
{% extends 'myapp/base.html' %}
{% block content %}

<h1>You have been logged out</h1>




{% endblock %}

users/templates/users/profile.html
{% extends 'myapp/base.html' %}
{% block content %}
<div class="grid p-10 gird-cols-1 lg:grid-cols-3 sm:grid-cols-1">
    <div class="rounded shadow-lg">
        <div>
            <img src="{{user.profile.image.url}}" alt="">

        </div>
        <div class="font-bold text-xl mb-2 px-6 py-4">
            {{user.username}}

        </div>
    </div>
</div>

{% endblock %}

users/templates/users/register.html
{% extends 'myapp/base.html' %}
{% block content %}

<h1 class="text-2xl m-10 font-bold">Register User</h1>
<div class="container ">
    <form class="w-2/5  bg-white shadow-md m-10 rounded px-8 pt-6 pb-8 mb-4 " method="POST">
        {% csrf_token %}
        <div class="mb-2">
            <label class="block text-gray-700 text-sm font-bold mb-2"for="">Username</label>
            <div class="shadow apperance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">
                {{ form.username }}
            </div>
        </div>
        <div class="mb-2">
            <label class="block text-gray-700 text-sm font-bold mb-2"for="">Email</label>
            <div class="shadow apperance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">
                {{ form.email }}
            </div>
        </div>
        <div class="mb-2">
            <label class="block text-gray-700 text-sm font-bold mb-2"for="">Password</label>
            <div class="shadow apperance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">
                {{ form.password1 }}
            </div>
        </div>
        <div class="mb-2">
            <label class="block text-gray-700 text-sm font-bold mb-2"for="">Confirm Password</label>
            <div class="shadow apperance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">
                {{ form.password2 }}
            </div>
        </div>
        <div class="pt-2">
            <button class="button bg-green-500 hover:bg-green-600 
            active:bg-green-700 focus:outline-none focus:ring-green-300 
            text-white px-6 py-2" type="submit">Register</button>
        </div>
    </form>
</div>



{% endblock %}